graph LR
  _07["Элементы"]
  07_ЭЛ_10["ЭЛ 10 Земляные сооружения, фундаменты"]
  07_ЭЛ --> 07_ЭЛ_10
  07_ЭЛ_10_10["ЭЛ 10 10 Фундаменты"]
  07_ЭЛ_10 --> 07_ЭЛ_10_10
  07_ЭЛ_10_20["ЭЛ 10 20 Подпорные стены"]
  07_ЭЛ_10 --> 07_ЭЛ_10_20
  07_ЭЛ_10_25["ЭЛ 10 25 Основание"]
  07_ЭЛ_10 --> 07_ЭЛ_10_25
  07_ЭЛ_10_30["ЭЛ 10 30 Компоненты для защиты фундаментов"]
  07_ЭЛ_10 --> 07_ЭЛ_10_30
  07_ЭЛ_10_40["ЭЛ 10 40 Земляные сооружения"]
  07_ЭЛ_10 --> 07_ЭЛ_10_40
  07_ЭЛ_20["ЭЛ 20 Крыша"]
  07_ЭЛ --> 07_ЭЛ_20
  07_ЭЛ_20_20["ЭЛ 20 20 Элементы конструкции крыши"]
  07_ЭЛ_20 --> 07_ЭЛ_20_20
  07_ЭЛ_20_30["ЭЛ 20 30 Компоненты для устройства кровли"]
  07_ЭЛ_20 --> 07_ЭЛ_20_30
  07_ЭЛ_20_90["ЭЛ 20 90 Армирование ЖБ элементов кровли"]
  07_ЭЛ_20 --> 07_ЭЛ_20_90
  07_ЭЛ_30["ЭЛ 30 Архитектурные и конструктивные элементы"]
  07_ЭЛ --> 07_ЭЛ_30
  07_ЭЛ_30_10["ЭЛ 30 10 Ограждающие конструкции"]
  07_ЭЛ_30 --> 07_ЭЛ_30_10
  07_ЭЛ_30_12["ЭЛ 30 12 Ограждения"]
  07_ЭЛ_30 --> 07_ЭЛ_30_12
  07_ЭЛ_30_14["ЭЛ 30 14 Проемы, ниши"]
  07_ЭЛ_30 --> 07_ЭЛ_30_14
  07_ЭЛ_30_16["ЭЛ 30 16 Элементы конструкций"]
  07_ЭЛ_30 --> 07_ЭЛ_30_16
  07_ЭЛ_30_18["ЭЛ 30 18 Окна, двери и ворота"]
  07_ЭЛ_30 --> 07_ЭЛ_30_18
  07_ЭЛ_30_19["ЭЛ 30 19 Доборные элементы"]
  07_ЭЛ_30 --> 07_ЭЛ_30_19
  07_ЭЛ_30_20["ЭЛ 30 20 Мусороудаление"]
  07_ЭЛ_30 --> 07_ЭЛ_30_20
  07_ЭЛ_30_24["ЭЛ 30 24 Лестницы и пандусы"]
  07_ЭЛ_30 --> 07_ЭЛ_30_24
  07_ЭЛ_30_25["ЭЛ 30 25 Печи, камины, очаги"]
  07_ЭЛ_30 --> 07_ЭЛ_30_25
  07_ЭЛ_30_26["ЭЛ 30 26 Отделка стен"]
  07_ЭЛ_30 --> 07_ЭЛ_30_26
  07_ЭЛ_30_28["ЭЛ 30 28 Отделка потолка"]
  07_ЭЛ_30 --> 07_ЭЛ_30_28
  07_ЭЛ_30_29["ЭЛ 30 29 Детали декоративные"]
  07_ЭЛ_30 --> 07_ЭЛ_30_29
  07_ЭЛ_30_30["ЭЛ 30 30 Вспомогательные 3D-тела и формы"]
  07_ЭЛ_30 --> 07_ЭЛ_30_30
  07_ЭЛ_30_32["ЭЛ 30 32 Отделка (состав) пола"]
  07_ЭЛ_30 --> 07_ЭЛ_30_32
  07_ЭЛ_30_80["ЭЛ 30 80 Закладные детали"]
  07_ЭЛ_30 --> 07_ЭЛ_30_80
  07_ЭЛ_30_90["ЭЛ 30 90 Армирование ж/б элементов"]
  07_ЭЛ_30 --> 07_ЭЛ_30_90
  07_ЭЛ_35["ЭЛ 35 Контроль прохода и управления доступом"]
  07_ЭЛ --> 07_ЭЛ_35
  07_ЭЛ_35_01["ЭЛ 35 01 Контроль прохода, доступа"]
  07_ЭЛ_35 --> 07_ЭЛ_35_01
  07_ЭЛ_40["ЭЛ 40 Инженерное оснащение"]
  07_ЭЛ --> 07_ЭЛ_40
  07_ЭЛ_40_10["ЭЛ 40 10 Подъемные и конвейерные механизмы"]
  07_ЭЛ_40 --> 07_ЭЛ_40_10
  07_ЭЛ_40_15["ЭЛ 40 15 Водоснабжение, водоотведение, отопление"]
  07_ЭЛ_40 --> 07_ЭЛ_40_15
  07_ЭЛ_40_20["ЭЛ 40 20 Вентиляция, кондиционирование"]
  07_ЭЛ_40 --> 07_ЭЛ_40_20
  07_ЭЛ_40_25["ЭЛ 40 25 Теплоснабжение"]
  07_ЭЛ_40 --> 07_ЭЛ_40_25
  07_ЭЛ_40_30["ЭЛ 40 30 Пожаротушение"]
  07_ЭЛ_40 --> 07_ЭЛ_40_30
  07_ЭЛ_40_35["ЭЛ 40 35 Трассировка кабелей"]
  07_ЭЛ_40 --> 07_ЭЛ_40_35
  07_ЭЛ_40_36["ЭЛ 40 36 Кабельно-проводниковая продукция"]
  07_ЭЛ_40 --> 07_ЭЛ_40_36
  07_ЭЛ_40_40["ЭЛ 40 40 Элементы наружного водостока"]
  07_ЭЛ_40 --> 07_ЭЛ_40_40
  07_ЭЛ_40_45["ЭЛ 40 45 Элементы крепления"]
  07_ЭЛ_40 --> 07_ЭЛ_40_45
  07_ЭЛ_40_50["ЭЛ 40 50 Оборудование"]
  07_ЭЛ_40 --> 07_ЭЛ_40_50
  07_ЭЛ_40_55["ЭЛ 40 55 Контрольно-измерительные приборы и аппа"]
  07_ЭЛ_40 --> 07_ЭЛ_40_55
  07_ЭЛ_40_60["ЭЛ 40 60 Элементы интерьера"]
  07_ЭЛ_40 --> 07_ЭЛ_40_60
  07_ЭЛ_40_62["ЭЛ 40 62 Спортивное оборудование"]
  07_ЭЛ_40 --> 07_ЭЛ_40_62
  07_ЭЛ_50["ЭЛ 50 Гидротехнические сооружения"]
  07_ЭЛ --> 07_ЭЛ_50
  07_ЭЛ_50_10["ЭЛ 50 10 Защитные сооружения"]
  07_ЭЛ_50 --> 07_ЭЛ_50_10
  07_ЭЛ_50_20["ЭЛ 50 20 Гидроэлектростанция (ГЭС)"]
  07_ЭЛ_50 --> 07_ЭЛ_50_20
  07_ЭЛ_60["ЭЛ 60 Железные дороги, метрополитен"]
  07_ЭЛ --> 07_ЭЛ_60
  07_ЭЛ_60_09["ЭЛ 60 09 Полоса отвода железной дороги"]
  07_ЭЛ_60 --> 07_ЭЛ_60_09
  07_ЭЛ_60_10["ЭЛ 60 10 Перегонные тоннели"]
  07_ЭЛ_60 --> 07_ЭЛ_60_10
  07_ЭЛ_60_20["ЭЛ 60 20 Верхнее строение пути, элементы пути"]
  07_ЭЛ_60 --> 07_ЭЛ_60_20
  07_ЭЛ_60_22["ЭЛ 60 22 Искусственные сооружения"]
  07_ЭЛ_60 --> 07_ЭЛ_60_22
  07_ЭЛ_60_30["ЭЛ 60 30 Аудио-видео связь"]
  07_ЭЛ_60 --> 07_ЭЛ_60_30
  07_ЭЛ_60_35["ЭЛ 60 35 Элементы кабеленесущих систем"]
  07_ЭЛ_60 --> 07_ЭЛ_60_35
  07_ЭЛ_60_40["ЭЛ 60 40 Кабельные соединения"]
  07_ЭЛ_60 --> 07_ЭЛ_60_40
  07_ЭЛ_60_45["ЭЛ 60 45 Участки кабельной линии"]
  07_ЭЛ_60 --> 07_ЭЛ_60_45
  07_ЭЛ_60_55["ЭЛ 60 55 Контрольно-измерительные приборы и аппа"]
  07_ЭЛ_60 --> 07_ЭЛ_60_55
  07_ЭЛ_70["ЭЛ 70 Автомобильные дороги"]
  07_ЭЛ --> 07_ЭЛ_70
  07_ЭЛ_70_10["ЭЛ 70 10 Полоса отвода автомобильной дороги"]
  07_ЭЛ_70 --> 07_ЭЛ_70_10
  07_ЭЛ_70_20["ЭЛ 70 20 Земляное полотно"]
  07_ЭЛ_70 --> 07_ЭЛ_70_20
  07_ЭЛ_70_30["ЭЛ 70 30 Линейная часть"]
  07_ЭЛ_70 --> 07_ЭЛ_70_30
  07_ЭЛ_70_40["ЭЛ 70 40 Поверхность дороги"]
  07_ЭЛ_70 --> 07_ЭЛ_70_40
  07_ЭЛ_70_50["ЭЛ 70 50 Санитарно-защитные зоны"]
  07_ЭЛ_70 --> 07_ЭЛ_70_50
  07_ЭЛ_70_60["ЭЛ 70 60 Искусственные сооружения"]
  07_ЭЛ_70 --> 07_ЭЛ_70_60
  07_ЭЛ_70_70["ЭЛ 70 70 Организация дорожного движения"]
  07_ЭЛ_70 --> 07_ЭЛ_70_70
  07_ЭЛ_70_80["ЭЛ 70 80 Дорожная одежда"]
  07_ЭЛ_70 --> 07_ЭЛ_70_80
  07_ЭЛ_90["ЭЛ 90 Оснащение серверных"]
  07_ЭЛ --> 07_ЭЛ_90
  07_ЭЛ_90_10["ЭЛ 90 10 Телекоммуникационные стойки и шкафы"]
  07_ЭЛ_90 --> 07_ЭЛ_90_10
  07_ЭЛ_91["ЭЛ 91 Проект организации строительства"]
  07_ЭЛ --> 07_ЭЛ_91
  07_ЭЛ_91_10["ЭЛ 91 10 Временные строительные конструкции"]
  07_ЭЛ_91 --> 07_ЭЛ_91_10
  07_ЭЛ_91_20["ЭЛ 91 20 Временные ограждения строительной площа"]
  07_ЭЛ_91 --> 07_ЭЛ_91_20
  07_ЭЛ_91_30["ЭЛ 91 30 Временные дороги"]
  07_ЭЛ_91 --> 07_ЭЛ_91_30
  07_ЭЛ["ЭЛ Элементы"]
  _07 --> 07_ЭЛ
